"""Domain specifications and immutable state views; no framework dependencies."""

from smartsom.domain.actions import TimedAction
from smartsom.domain.arrivals import ArrivalPlan, JobArrival, VisibleJob
from smartsom.domain.buffers import (
    BufferReservation,
    BufferState,
    HoldingBuffer,
    HoldingBufferState,
    HoldingReservation,
    MachineBuffers,
    MachineHolding,
)
from smartsom.domain.machine_events import MachineOutage, MachineOutagePlan
from smartsom.domain.models import (
    DomainValidationError,
    FactorySpec,
    Job,
    Machine,
    Operation,
    Order,
    ProcessingMode,
    WorkloadInstance,
    validate_problem,
)
from smartsom.domain.processing_times import ProcessingTime, ProcessingTimePlan
from smartsom.domain.state import (
    MachineState,
    OperationState,
    OperationStatus,
    ScheduledOperation,
)
from smartsom.domain.transport import (
    AGV,
    ActiveTransport,
    AGVState,
    ExecutionSchedule,
    JobLocation,
    JobPosition,
    MachineLocation,
    ScheduledTransfer,
    ScheduledTransport,
    TransportArrival,
    TransportDestination,
    TransportSpec,
    TravelTime,
)

__all__ = [
    "HoldingBuffer",
    "HoldingBufferState",
    "HoldingReservation",
    "MachineBuffers",
    "BufferState",
    "BufferReservation",
    "MachineHolding",
    "TimedAction",
    "ActiveTransport",
    "TransportArrival",
    "ScheduledTransfer",
    "AGV",
    "AGVState",
    "MachineLocation",
    "TravelTime",
    "TransportSpec",
    "TransportDestination",
    "JobLocation",
    "JobPosition",
    "ScheduledTransport",
    "ExecutionSchedule",
    "ArrivalPlan",
    "JobArrival",
    "VisibleJob",
    "DomainValidationError",
    "FactorySpec",
    "Job",
    "Machine",
    "MachineOutage",
    "MachineOutagePlan",
    "MachineState",
    "Operation",
    "OperationState",
    "OperationStatus",
    "Order",
    "ProcessingMode",
    "ProcessingTime",
    "ProcessingTimePlan",
    "ScheduledOperation",
    "WorkloadInstance",
    "validate_problem",
]
