schema: smartsom.scenario/v1
factory: ../factories/factory_test.yaml
workload:
  kind: instance
  path: ../../data/instances/processing_times.json
processing_time:
  kind: fixed
  path: ../../data/processing_times/hand.json
