schema: smartsom.algorithm/v1
algorithm:
  provider: builtin.scripted
  parameters:
    commands:
    - agvs:
      - - agv
        - DOWN
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - machines:
      - - M1
        - job_id: A/attempt/1
          mode_id: normal
    - {}
    - machines:
      - - M1
        - job_id: B/attempt/1
          mode_id: normal
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - machines:
      - - M1
        - job_id: C/attempt/1
          mode_id: normal
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - LEFT
    - agvs:
      - - agv
        - INTERACT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - RIGHT
    - agvs:
      - - agv
        - INTERACT
